from app.models import db, members

def seed_members():
    demo = members.insert().values(server_id =1,user_id= 1)
    marnie = members.insert().values(server_id =2,user_id= 2)
    bobbie = members.insert().values(server_id =3,user_id= 3)
    ali = members.insert().values(server_id=4, user_id=4)
    tristan = members.insert().values(server_id=5, user_id=5)
    edwin = members.insert().values(server_id=6, user_id=6)
    angel = members.insert().values(server_id=7,user_id=7)
    brad = members.insert().values(server_id=8,user_id=8)
    leah = members.insert().values(server_id=9,user_id=9)
    jeff = members.insert().values(server_id=10, user_id=10)
    john = members.insert().values(server_id=11, user_id=11)
    chris = members.insert().values(server_id=12, user_id=12)
    naruto = members.insert().values(server_id=13, user_id=13)
    sasuke = members.insert().values(server_id=14, user_id=14)
    sakura = members.insert().values(server_id=15, user_id=15)


    # leaf village
    naruto_leaf = members.insert().values(server_id =16,user_id= 13)
    sakura_leaf = members.insert().values(server_id =16,user_id= 15)
    sasuke_leaf = members.insert().values(server_id =16,user_id= 14)
    demo_leaf = members.insert().values(server_id =16,user_id= 1)

    # aa
    demo_aa = members.insert().values(server_id =17,user_id= 1)
    marnie_aa = members.insert().values(server_id =17,user_id= 2)
    bobbie_aa = members.insert().values(server_id =17,user_id= 3)
    ali_aa = members.insert().values(server_id =17,user_id= 4)
    tristan_aa = members.insert().values(server_id =17,user_id= 5)
    edwin_aa = members.insert().values(server_id =17,user_id= 6)
    angel_aa = members.insert().values(server_id =17,user_id= 7)
    brad_aa = members.insert().values(server_id =17,user_id= 8)
    leah_aa = members.insert().values(server_id =17,user_id= 9)
    jeff_aa = members.insert().values(server_id =17,user_id= 10)
    john_aa = members.insert().values(server_id =17,user_id= 11)
    chris_aa = members.insert().values(server_id =17,user_id= 12)

    # group
    demo_group = members.insert().values(server_id =18,user_id= 1)
    ali_group = members.insert().values(server_id =18,user_id= 4)
    tristan_group = members.insert().values(server_id =18,user_id= 5)
    edwin_group = members.insert().values(server_id =18,user_id= 6)
    angel_group = members.insert().values(server_id =18,user_id= 7)

    #test
    demo_test = members.insert().values(server_id =19,user_id= 1)

    db.engine.execute(demo)
    db.engine.execute(marnie)
    db.engine.execute(bobbie)
    db.engine.execute(ali)
    db.engine.execute(tristan)
    db.engine.execute(edwin)
    db.engine.execute(angel)
    db.engine.execute(brad)
    db.engine.execute(leah)
    db.engine.execute(jeff)
    db.engine.execute(john)
    db.engine.execute(chris)
    db.engine.execute(naruto)
    db.engine.execute(sasuke)
    db.engine.execute(sakura)
    db.engine.execute(naruto_leaf)
    db.engine.execute(sasuke_leaf)
    db.engine.execute(sakura_leaf)
    db.engine.execute(demo_leaf)
    db.engine.execute(demo_aa)
    db.engine.execute(ali_aa)
    db.engine.execute(tristan_aa)
    db.engine.execute(marnie_aa)
    db.engine.execute(bobbie_aa)
    db.engine.execute(edwin_aa)
    db.engine.execute(angel_aa)
    db.engine.execute(brad_aa)
    db.engine.execute(leah_aa)
    db.engine.execute(jeff_aa)
    db.engine.execute(john_aa)
    db.engine.execute(chris_aa)
    db.engine.execute(ali_group)
    db.engine.execute(edwin_group)
    db.engine.execute(tristan_group)
    db.engine.execute(angel_group)
    db.engine.execute(demo_group)
    db.engine.execute(demo_test)



    db.session.commit()
