from app.models import db, Server


def seed_servers():
    demo_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=1)
    marnie_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=2)
    bobbie_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=3)
    ali_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=4)
    tristan_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=5)
    edwin_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=6)
    angel_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=7)
    brad_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=8)
    leah_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=9)
    jeff_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=10)
    john_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=11)
    chris_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=12)
    naruto_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=13)
    sasuke_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=14)
    sakura_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=15)
    lee_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=16)
    hinata_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=17)
    kikashi_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=18)
    shikamaru_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=19)
    jiraiya_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=20)
    itachi_server= Server(name='@me', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=21)
    leaf_village = Server(name='Leaf Village', image='https://bitchenstickerz.com/wp-content/uploads/2017/08/NarutoLeaf.jpg', owner_id=13)
    aaonline= Server(name='AppAcademy', image='https://assets-global.website-files.com/5dcc7f8c449e597ed83356b8/603820afd31232aab368ea6f_New%20Red-logo-emblem.png', owner_id=8)
    group_project= Server(name='Group-Project', image='https://discord-imgs.s3.us-east-2.amazonaws.com/1-discord.png', owner_id=6)
    test =Server(name='Demo Server', image='https://discord-imgs.s3.us-east-2.amazonaws.com/discord-server.png', owner_id=1)

    db.session.add(demo_server)
    db.session.add(marnie_server)
    db.session.add(bobbie_server)
    db.session.add(ali_server)
    db.session.add(tristan_server)
    db.session.add(edwin_server)
    db.session.add(angel_server)
    db.session.add(brad_server)
    db.session.add(leah_server)
    db.session.add(jeff_server)
    db.session.add(john_server)
    db.session.add(chris_server)
    db.session.add(naruto_server)
    db.session.add(sasuke_server)
    db.session.add(sakura_server)
    db.session.add(lee_server)
    db.session.add(hinata_server)
    db.session.add(shikamaru_server)
    db.session.add(kikashi_server)
    db.session.add(jiraiya_server)
    db.session.add(itachi_server)
    db.session.add(leaf_village)
    db.session.add(aaonline)
    db.session.add(group_project)
    db.session.add(test)

    db.session.commit()
